import json
import os
import subprocess
import pandas as pd
from io import BytesIO

from scenarioData import get_data


def test():
    data_dict = get_data()
    df = pd.DataFrame([data_dict])
    df.to_excel('test.xlsx', index=False)

    # Add the Excel file to the Git staging area
    subprocess.run(['git', 'add', 'test.xlsx'], check=True)

    # Commit the Excel file with a message
    commit_message = 'Add Excel file generated by GitHub Actions workflow'
    subprocess.run(['git', 'commit', '-m', commit_message], check=True)

    # Push the changes back to the repository
    subprocess.run(['git', 'push'], check=True)


if __name__ == '__main__':
    test()



