name: run_model
on:
  workflow_dispatch:
    inputs:
      json_vars:
        description: 'JSON-encoded string of scenario variables'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        id: run_script
        run: |
          result=$(python main.py)
          echo "RESULT=$result" >> $GITHUB_ENV
        env:
          JSON_VARS: ${{ github.event.inputs.json_vars }}

      - name: Set output
        id: set_output
        run: |
          echo "result=${{ env.RESULT }}" >> $GITHUB_ENV