name: run_model
on:
  workflow_dispatch:
    inputs:
      scenarioName:
        description: 'Name of the scenario'
        required: true
      insurancePrice:
        description: 'Price of insurance'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          SCENARIO_NAME: ${{ github.event.inputs.scenarioName }}
          INSURANCE_PRICE: ${{ github.event.inputs.insurancePrice }}